package model

const LOGIN_FAILED = 100

const REGISTER_FAILED_WONT_SAVE_TO_DATABASE = 110
const REGISTER_FAILED_EMAIL_ALREADY_EXISTS = 111

const ORDER_FAILED_PRODUCT_NOT_AVAILABLE_FOR_RENTING = 120
const ORDER_FAILED_RENT_DURATION_EXCEEDS_PRODUCT_MAX_RENT_DURATION = 121
const ORDER_FAILED_PRODUCT_ID_NOT_FOUND = 122
const ORDER_FAILED_QUANTITY_EXCEEDS_PRODUCT_QUANTITY = 123
const ORDER_FAILED_BORROWER_ID_NOT_FOUND = 124
const ORDER_FAILED_RENT_DURATION_DOESNT_MEET_MINIMUM_RENT_DURATION = 125
const ORDER_FAILED_BORROWER_IS_THE_TENANT = 126

const PRODUCT_NOT_FOUND = 130

const ORDER_NOT_FOUND = 140

const ORDER_CANCELLATION_FAILED = 150

const UPLOAD_PRODUCT_FAILED_PRICE_IS_ZERO_OR_BELOW = 160
const UPLOAD_PRODUCT_FAILED_QUANTITY_IS_ZERO_OR_BELOW = 161
const UPLOAD_PRODUCT_FAILED_TENANT_ID_NOT_EXISTS = 162
const UPLOAD_PRODUCT_FAILED_CATEGORY_ID_NOT_EXISTS = 163
const UPLOAD_PRODUCT_FAILED_FILE_TOO_BIG = 164
const UPLOAD_PRODUCT_FAILED_INVALID_FILE = 165

const GET_ALL_ORDERS_FAILED_USER_ID_NOT_FOUND = 170
const GET_ALL_ORDERS_FAILED_SQL_ERROR = 171