package model

const LOGIN_FAILED = 100

const REGISTER_FAILED_BLANK_FIELD_FOUND = 110
const REGISTER_FAILED_EMAIL_ALREADY_EXISTS = 111

const ORDER_FAILED_PRODUCT_NOT_AVAILABLE_FOR_RENTING = 120
const ORDER_FAILED_RENT_DURATION_EXCEEDS_PRODUCT_MAX_RENT_DURATION = 121

const PRODUCT_NOT_FOUND = 130